name: wistl
channels:
- IOOS
dependencies:
- cycler=0.9.0=py27_0
- freetype=2.5.5=0
- geos=3.4.2=0      
- hdf5=1.8.15.1=2
- libpng=1.6.17=0
- matplotlib=1.5.1=np110py27_0
- mkl=11.3.1=0          
- numexpr=2.4.6=np110py27_0
- numpy=1.10.2=py27_0
- openssl=1.0.2e=0
- pandas=0.17.1=np110py27_0
- pip=7.1.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- pytables=3.2.2=np110py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.16.1=np110py27_1
- setuptools=19.2=py27_0
- shapely=1.5.13=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- geopy=1.11.0

# added for ipython notebook
- appnope=0.1.0=py27_0
- decorator=4.0.9=py27_0
- ipython=4.1.2=py27_2
- ipython_genutils=0.1.0=py27_0
- path.py=8.1.2=py27_1
- pexpect=4.0.1=py27_0
- pickleshare=0.5=py27_0
- ptyprocess=0.5=py27_0
- simplegeneric=0.8.1=py27_0
- traitlets=4.2.1=py27_0

- pip:
  - parmap==1.2.3
  - pyshp==1.2.3
  - tables==3.2.2

