name: wistl
channels:
- IOOS
dependencies:
- cycler=0.9.0=py27_0
- freetype=2.5.5=0
- geos=3.4.2=0      
- hdf5=1.8.15.1=2
- libpng=1.6.17=0
- matplotlib=1.5.1=np110py27_0
- mkl=11.3.1=0          
- numexpr=2.4.6=np110py27_0
- numpy=1.10.2=py27_0
- openssl=1.0.2e=0
- pandas=0.17.1=np110py27_0
- pip=7.1.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- pytables=3.2.2=np110py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.16.1=np110py27_1
- setuptools=19.2=py27_0
- shapely=1.5.13=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- IOOS::geopy=1.10.0

# added for ipython notebook
- appnope=0.1.0=py27_0
- decorator=4.0.9=py27_0
- ipython=4.1.2=py27_2
- ipython_genutils=0.1.0=py27_0
- path.py=8.1.2=py27_1
- pexpect=4.0.1=py27_0
- pickleshare=0.5=py27_0
- ptyprocess=0.5=py27_0
- simplegeneric=0.8.1=py27_0
- traitlets=4.2.1=py27_0

# added for ipython notebook

- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- configparser=3.5.0b2=py27_1
- entrypoints=0.2=py27_1
- get_terminal_size=1.0.0=py27_0
- ipykernel=4.3.1=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.4.0=py27_0
- jupyter_client=4.2.2=py27_0
- jupyter_core=4.1.0=py27_0
- markupsafe=0.23=py27_0
- mistune=0.7.2=py27_1
- nbconvert=4.2.0=py27_0
- nbformat=4.0.1=py27_0
- notebook=4.2.0=py27_0
- pygments=2.1.3=py27_0
- pyzmq=15.2.0=py27_0
- singledispatch=3.4.0.3=py27_0
- ssl_match_hostname=3.4.0.2=py27_1
- terminado=0.5=py27_1
- tornado=4.3=py27_0


- pip:
  - parmap==1.2.3
  - pyshp==1.2.3
  - tables==3.2.2

